mp.messaging.incoming.words-in.auto.offset.reset=earliest
mp.messaging.incoming.words-in.topic=words
mp.messaging.outgoing.words-out.topic=words
#quarkus.devservices.enabled=false
server.port=8081

quarkus.datasource.jdbc.url=${BOOKING_DB_URL}
quarkus.datasource.db-kind=${BOOKING_DB_KIND}
quarkus.datasource.username=${BOOKING_DB_USERNAME}
quarkus.datasource.password=${BOOKING_DB_PASSWORD}

# quarkus.grpc.server.use-separate-server=false
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}

%test.quarkus.hibernate-orm.log.sql=true

quarkus.rest-client.hotelio-api.url=${hotelio.api.host}
quarkus.rest-client.hotelio-api.disable-default-mapper=true
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=1024
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG