apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: booking-service-dr
spec:
  host: booking-service
  subsets:
    - name: v1
      labels:
        app: booking-service
    - name: v2
      labels:
        app: booking-service-v2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      maxEjectionPercent: 50
