apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: booking-service-external-vs
spec:
  hosts:
    - booking-service
  gateways:
    - booking-service-gw
  http:
    - route:
        - destination:
            host: booking-service
            subset: v1
            port:
              number: 8080
          weight: 90
        - destination:
            host: booking-service
            subset: v2
            port:
              number: 8080
          weight: 10
      retries:
        attempts: 1
        retryOn: 5xx
        perTryTimeout: 2s
