apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: booking-service-gw
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 9090
      name: http
      protocol: HTTP
    hosts:
    - 176.123.164.234
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - 176.123.164.234
