apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: booking-service-gw
  namespace: istio-system
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 9090
      name: http-9090
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 8080
      name: http-8080
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 30171
      name: http-30171
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 30707
      name: http-30707
      protocol: HTTP
    hosts:
    - "*"
